name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Install dependencies
        run: yarn
      - name: Type Check
        run: yarn tsc --noEmit
      - name: Check ESLint rules
        run: yarn lint
      - name: Run test
        run: yarn test
        env:
          TITLE: ${{ github.repository_owner }}/twitter-github-contribution-graph
